language: go

go:
  - 1.13.x

before_install:
  - go mod vendor
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.19.1

script:
  - go test -race -cover ./...

notifications:
email: false
